name: Compile Test
on: workflow_dispatch
jobs:
  Build:
    runs-on: dara-macbook-pro
    steps:
      - name: Checkout-Mac
        uses: actions/checkout@v3
        with:
          clean: false
          path: PlatformMac
      - name: SetPicoDefineOn
        run: /Applications/Unity/Hub/Editor/2021.3.7f1/Unity.app/Contents/MacOS/Unity -batchmode -quit -logFile -projectPath ./PlatformMac -executeMethod DefineSymbolsEditor.SetPicoOn -nographics -logFile
      - name: BuildMac
        run: /Applications/Unity/Hub/Editor/2021.3.7f1/Unity.app/Contents/MacOS/Unity -batchmode -quit -logFile -projectPath ./PlatformMac -executeMethod Build.BuildReleaseMac -nographics -logFile