name: Return Value Test
on: workflow_dispatch
jobs:
  Experiment:
    runs-on: dara-macbook-pro
    steps:
    - name: Checkout-Windows
      uses: actions/checkout@v3
      with:
        clean: false
        path: PlatformWindows
    - name: return-value
      id: return-value
      run: /Applications/Unity/Hub/Editor/2021.3.7f1/Unity.app/Contents/MacOS/Unity -batchmode -quit -logFile -projectPath ./PlatformWindows -executeMethod ReturnValue.CreateOutput -nographics -logFile
    - name: Set environment variables from Unity output
      run: |
        while read line; do
          echo "$line" >> $GITHUB_ENV
        done < /Users/kota/actions-runner/first_action_runner/CICDBuildSample/CICDBuildSample/PlatformWindows/Build/test.txt
    - name: Use environment variables in subsequent steps
      run: |
        echo "Variable1: ${{ env.VARIABLE1 }}"
        echo "Variable2: ${{ env.VARIABLE2 }}"
        echo "Variable3: ${{ env.VARIABLE3 }}"
