name: Return Value Test
on: workflow_dispatch
jobs:
  Experiment:
    runs-on: dara-macbook-pro
    outputs:
      month: ${{ steps.return-value.outputs.return }}
    steps:
    - name: Checkout-Windows
      uses: actions/checkout@v3
      with:
        clean: false
        path: PlatformWindows
    - name: return-value
      id: return-value
      run: |
        return=$(/Applications/Unity/Hub/Editor/2021.3.7f1/Unity.app/Contents/MacOS/Unity -batchmode -quit -logFile -projectPath ./PlatformWindows -executeMethod ReturnValue.ReturnValueMethod -nographics -logFile)
        echo "return=$return" >> $GITHUB_OUTPUT
    - name: display-value
      run: echo "The return value is ${{ steps.return-value.outputs.return }}"