name: Return Value Test
on: workflow_dispatch
jobs:
  Experiment:
    runs-on: dara-macbook-pro
    steps:
    - name: Checkout-Windows
      uses: actions/checkout@v3
      with:
        clean: false
        path: PlatformWindows
    - name: return-value
      id: return-value
      run: /Applications/Unity/Hub/Editor/2021.3.7f1/Unity.app/Contents/MacOS/Unity -batchmode -quit -logFile -projectPath ./PlatformWindows -executeMethod ReturnValue.CreateOutput -nographics -logFile
    - name: Set environment variables from Unity output
      id: set-env
      run: |
        while read line; do
          echo "$line" >> $GITHUB_OUTPUT
        done < ./PlatformWindows/Build/test.txt
    - name: Use environment variables in subsequent steps
      run: |
        echo "Variable1: ${{ steps.set-env.outputs.VARIABLE1 }}"
    - name: ShellScript
      run: ./PlatformWindows/ShellScripts/test_run.sh ${{ env.VARIABLE1 }}
